#!/usr/bin/env python3
"""Import the canonical SerialLeg loop-joint URDF into a validated USD asset.

The Isaac Sim URDF importer creates a reduced-coordinate articulation from the
ten tree joints and emits the two custom ``loop_joint`` elements as external
``PhysicsSphericalJoint`` constraints.  This script makes the critical
``excludeFromArticulation`` opinions explicit, restores the MJCF joint
armatures, flattens the imported stage, and validates the saved artifact.  The
canonical URDF and runtime USD are both collision-only; import adds only tiny
transient dummy visuals required by the importer and removes them before save.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import math
import os
import sys
import tempfile
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = PROJECT_ROOT / "source/se3_rl_lab/se3_rl_lab/assets/robots/serialleg"


def _load_serialleg_contract() -> Any:
    """Load the pure-Python contract module without importing the IsaacLab extension package."""
    module_path = ASSET_DIR.parent / "serialleg_contract.py"
    module_name = "_se3_rl_lab_serialleg_contract"
    spec = importlib.util.spec_from_file_location(module_name, module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"failed to load SerialLeg contract module: {module_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module.load_serialleg_contract(ASSET_DIR / "serialleg_contract.toml")


SERIALLEG_CONTRACT = _load_serialleg_contract()
CONTRACT_PATH = ASSET_DIR / "serialleg_contract.toml"
CONTRACT_SHA256 = hashlib.sha256(CONTRACT_PATH.read_bytes()).hexdigest()
DEFAULT_URDF = ASSET_DIR / SERIALLEG_CONTRACT.canonical_urdf
DEFAULT_OUTPUT = ASSET_DIR / SERIALLEG_CONTRACT.runtime_usd

EXPECTED_ROBOT_NAME = SERIALLEG_CONTRACT.robot_name
EXPECTED_LINKS = set(SERIALLEG_CONTRACT.links)
EXPECTED_TREE_JOINTS = {
    name: (joint.parent, joint.child, joint.armature) for name, joint in SERIALLEG_CONTRACT.tree_joints.items()
}
EXPECTED_LOOPS = {
    name: (loop.body0, loop.local_pos0, loop.body1, loop.local_pos1)
    for name, loop in SERIALLEG_CONTRACT.loop_joints.items()
}
EXPECTED_LOOP_ARMATURES = {name: loop.armature for name, loop in SERIALLEG_CONTRACT.loop_joints.items()}
if len(set(EXPECTED_LOOP_ARMATURES.values())) != 1:
    raise RuntimeError("SerialLeg loop joints must currently share one armature value")
LOOP_JOINT_ARMATURE = next(iter(EXPECTED_LOOP_ARMATURES.values()))

EXPECTED_TOTAL_MASS = SERIALLEG_CONTRACT.usd_gate.expected_total_mass
EXPECTED_URDF_SHA256 = "280d74c4aa7b9f1ee98c10aaabb77efe15fe9b965363ea8b67c86fdad440dd3e"
EXPECTED_VISUAL_COUNT = SERIALLEG_CONTRACT.usd_gate.expected_visual_count
EXPECTED_COLLISION_MESH_COUNT = SERIALLEG_CONTRACT.usd_gate.expected_collision_mesh_count
EXPECTED_COLLISION_FACE_COUNT = SERIALLEG_CONTRACT.usd_gate.expected_collision_face_count
EXPECTED_COLLISION_POINT_INDEX_COUNT = SERIALLEG_CONTRACT.usd_gate.expected_collision_point_index_count
MAX_COLLISION_ONLY_USD_BYTES = SERIALLEG_CONTRACT.usd_gate.max_collision_only_usd_bytes
DUMMY_VISUAL_RADIUS = "1e-6"
VISUAL_POLICY = "transient-transparent-dummy-then-remove:collision-only"
STAGE_DOCUMENTATION = (
    "Generated by scripts/convert_serialleg_urdf_to_usd.py from the canonical SerialLeg loop-joint URDF."
)
FLOAT_TOLERANCE = 1.0e-6
EXPECTED_JOINT_DAMPING = {name: joint.source_damping for name, joint in SERIALLEG_CONTRACT.tree_joints.items()}
EXPECTED_JOINT_FRICTION = {name: joint.source_friction for name, joint in SERIALLEG_CONTRACT.tree_joints.items()}

IMPORTER_SETTINGS = dict(SERIALLEG_CONTRACT.usd_importer)


class ConversionError(RuntimeError):
    """Raised when the source or generated USD violates the asset contract."""


@dataclass(frozen=True)
class SourceContract:
    """Validated URDF metadata needed by the USD conversion gate."""

    sha256: str
    relative_path: str


@dataclass(frozen=True)
class StageInventory:
    """Physics objects collected from a reopened USD stage."""

    links: dict[str, Any]
    rigid_bodies: list[Any]
    articulation_roots: list[Any]
    revolute_joints: dict[str, Any]
    spherical_joints: dict[str, Any]
    unexpected_joints: list[Any]
    geometry_prims: list[Any]
    collision_geometry: list[Any]
    visual_geometry: list[Any]
    meshes: list[Any]
    non_collision_geometry: list[Any]
    authored_non_collision_geometry: list[Any]
    collision_roots: list[Any]
    visual_roots: list[Any]
    collision_api_prims: list[Any]
    mesh_collision_api_prims: list[Any]
    cylinders: list[Any]
    capsules: list[Any]


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--urdf", type=Path, default=DEFAULT_URDF, help="Canonical loop-joint URDF")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Destination flattened USD")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate the existing USD against the current URDF without importing or writing",
    )
    return parser.parse_args()


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _relative_project_path(path: Path) -> str:
    try:
        return path.resolve().relative_to(PROJECT_ROOT.resolve()).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def _parse_vector(text: str | None, context: str) -> tuple[float, float, float]:
    if text is None:
        raise ConversionError(f"{context} is missing xyz")
    values = tuple(float(value) for value in text.split())
    if len(values) != 3:
        raise ConversionError(f"{context} expected a 3-vector, got {text!r}")
    return values  # type: ignore[return-value]


def _assert_close(actual: float, expected: float, context: str, tolerance: float = FLOAT_TOLERANCE) -> None:
    if not math.isclose(actual, expected, rel_tol=0.0, abs_tol=tolerance):
        raise ConversionError(f"{context}: expected {expected:.12g}, got {actual:.12g}")


def _assert_vector_close(actual: Any, expected: tuple[float, float, float], context: str) -> None:
    values = tuple(float(value) for value in actual)
    if len(values) != 3:
        raise ConversionError(f"{context}: expected 3 values, got {values!r}")
    for index, (actual_value, expected_value) in enumerate(zip(values, expected, strict=True)):
        _assert_close(actual_value, expected_value, f"{context}[{index}]")


def _validate_urdf(urdf_path: Path) -> SourceContract:
    if not urdf_path.is_file():
        raise ConversionError(f"URDF does not exist: {urdf_path}")

    root = ET.parse(urdf_path).getroot()
    if root.tag != "robot" or root.attrib.get("name") != EXPECTED_ROBOT_NAME:
        raise ConversionError(f"unexpected robot root/name in {urdf_path}")

    links = {element.attrib.get("name", "") for element in root.findall("link")}
    if links != EXPECTED_LINKS:
        raise ConversionError(f"URDF link set changed: expected {sorted(EXPECTED_LINKS)}, got {sorted(links)}")

    joints = {element.attrib.get("name", ""): element for element in root.findall("joint")}
    if set(joints) != set(EXPECTED_TREE_JOINTS):
        raise ConversionError(
            f"URDF tree joint set changed: expected {sorted(EXPECTED_TREE_JOINTS)}, got {sorted(joints)}"
        )
    for name, (expected_parent, expected_child, _armature) in EXPECTED_TREE_JOINTS.items():
        joint = joints[name]
        if joint.attrib.get("type") != "continuous":
            raise ConversionError(f"{name} must remain continuous; coupled limits are not independent URDF limits")
        parent = joint.find("parent")
        child = joint.find("child")
        if parent is None or parent.attrib.get("link") != expected_parent:
            raise ConversionError(f"{name} parent changed from {expected_parent}")
        if child is None or child.attrib.get("link") != expected_child:
            raise ConversionError(f"{name} child changed from {expected_child}")
        dynamics = joint.find("dynamics")
        if dynamics is None:
            raise ConversionError(f"{name} is missing source dynamics metadata")
        _assert_close(
            float(dynamics.attrib.get("damping", "nan")),
            EXPECTED_JOINT_DAMPING[name],
            f"{name} source damping",
        )
        _assert_close(
            float(dynamics.attrib.get("friction", "nan")),
            EXPECTED_JOINT_FRICTION[name],
            f"{name} source friction",
        )

    loop_elements = {element.attrib.get("name", ""): element for element in root.findall("loop_joint")}
    if set(loop_elements) != set(EXPECTED_LOOPS):
        raise ConversionError(
            f"URDF loop joint set changed: expected {sorted(EXPECTED_LOOPS)}, got {sorted(loop_elements)}"
        )
    for name, (link0, position0, link1, position1) in EXPECTED_LOOPS.items():
        loop = loop_elements[name]
        if loop.attrib.get("type") != "spherical":
            raise ConversionError(f"{name} must remain a spherical loop_joint")
        endpoint0 = loop.find("link1")
        endpoint1 = loop.find("link2")
        if endpoint0 is None or endpoint0.attrib.get("link") != link0:
            raise ConversionError(f"{name} link1 changed from {link0}")
        if endpoint1 is None or endpoint1.attrib.get("link") != link1:
            raise ConversionError(f"{name} link2 changed from {link1}")
        _assert_vector_close(_parse_vector(endpoint0.attrib.get("xyz"), f"{name}.link1"), position0, f"{name}.link1")
        _assert_vector_close(_parse_vector(endpoint1.attrib.get("xyz"), f"{name}.link2"), position1, f"{name}.link2")
        if endpoint0.attrib.get("rpy", "0 0 0") != "0 0 0" or endpoint1.attrib.get("rpy", "0 0 0") != "0 0 0":
            raise ConversionError(f"{name} loop endpoint orientation must remain identity")

    visual_count = len(root.findall("link/visual"))
    if visual_count != EXPECTED_VISUAL_COUNT:
        raise ConversionError(f"expected {EXPECTED_VISUAL_COUNT} visual elements, got {visual_count}")

    collision_mesh_count = len(root.findall("link/collision/geometry/mesh"))
    if collision_mesh_count != EXPECTED_COLLISION_MESH_COUNT:
        raise ConversionError(
            f"expected {EXPECTED_COLLISION_MESH_COUNT} collision mesh references, got {collision_mesh_count}"
        )

    mesh_count = 0
    for mesh in root.findall(".//mesh"):
        filename = mesh.attrib.get("filename")
        if not filename:
            raise ConversionError("URDF contains a mesh without filename")
        mesh_count += 1
        mesh_path = (urdf_path.parent / filename).resolve()
        if not mesh_path.is_file():
            raise ConversionError(f"URDF mesh does not exist: {mesh_path}")
    if mesh_count != EXPECTED_COLLISION_MESH_COUNT:
        raise ConversionError(f"expected {EXPECTED_COLLISION_MESH_COUNT} mesh references, got {mesh_count}")

    total_mass = sum(float(element.attrib["value"]) for element in root.findall("link/inertial/mass"))
    _assert_close(total_mass, EXPECTED_TOTAL_MASS, "URDF total mass", tolerance=1.0e-8)

    source_sha256 = _sha256(urdf_path)
    if source_sha256 != EXPECTED_URDF_SHA256:
        raise ConversionError(
            "canonical URDF bytes changed; rerun the MJCF→URDF --check gate and review/update the USD contract"
        )
    return SourceContract(sha256=source_sha256, relative_path=_relative_project_path(urdf_path))


def _build_collision_only_import_urdf(urdf_path: Path, temporary_root: Path) -> Path:
    """Create importer input with transient dummy visuals.

    Zero-face mesh files are not valid geometry for every importer.  The Isaac
    importer also creates dangling ``visuals`` references for links with no
    visual at all, so each link receives one tiny transparent sphere following
    the Kyber importer workaround.  Those transient scopes are removed from the
    imported stage before flattening.  Collision, inertia, tree joints, and
    loop joints stay sourced from the already validated canonical document.
    """
    tree = ET.parse(urdf_path)
    root = tree.getroot()

    stripped_visual_count = 0
    for link in root.findall("link"):
        visual_elements = list(link.findall("visual"))
        stripped_visual_count += len(visual_elements)
        for visual in visual_elements:
            link.remove(visual)
    if stripped_visual_count != EXPECTED_VISUAL_COUNT:
        raise ConversionError(
            f"temporary importer URDF stripped {stripped_visual_count} visuals; expected {EXPECTED_VISUAL_COUNT}"
        )
    for link in root.findall("link"):
        visual = ET.SubElement(link, "visual", {"name": "__se3_rl_lab_dummy_visual__"})
        ET.SubElement(visual, "origin", {"xyz": "0 0 0", "rpy": "0 0 0"})
        geometry = ET.SubElement(visual, "geometry")
        ET.SubElement(geometry, "sphere", {"radius": DUMMY_VISUAL_RADIUS})
        material = ET.SubElement(visual, "material", {"name": "__se3_rl_lab_dummy_visual__"})
        ET.SubElement(material, "color", {"rgba": "0 0 0 0"})

    dummy_visuals = root.findall("link/visual")
    if len(dummy_visuals) != len(EXPECTED_LINKS):
        raise ConversionError(
            f"temporary importer URDF expected {len(EXPECTED_LINKS)} dummy visuals, got {len(dummy_visuals)}"
        )
    if root.findall("link/visual/geometry/mesh"):
        raise ConversionError("temporary importer URDF retained a visual mesh")
    for visual in dummy_visuals:
        sphere = visual.find("geometry/sphere")
        if sphere is None or sphere.attrib.get("radius") != DUMMY_VISUAL_RADIUS:
            raise ConversionError("temporary importer URDF contains a non-dummy visual geometry")

    collision_meshes = root.findall("link/collision/geometry/mesh")
    if len(collision_meshes) != EXPECTED_COLLISION_MESH_COUNT:
        raise ConversionError(
            "temporary importer URDF collision mesh set changed: "
            f"expected {EXPECTED_COLLISION_MESH_COUNT}, got {len(collision_meshes)}"
        )
    if len(root.findall(".//mesh")) != EXPECTED_COLLISION_MESH_COUNT:
        raise ConversionError("temporary importer URDF contains a mesh outside collision geometry")

    # The temporary URDF lives outside the asset tree.  Resolve retained mesh
    # paths so importer behavior does not depend on the temporary directory.
    for mesh in collision_meshes:
        filename = mesh.attrib.get("filename")
        if not filename:
            raise ConversionError("temporary importer URDF contains a collision mesh without filename")
        mesh_path = (urdf_path.parent / filename).resolve()
        if not mesh_path.is_file():
            raise ConversionError(f"temporary importer collision mesh does not exist: {mesh_path}")
        mesh.set("filename", mesh_path.as_posix())

    import_urdf_path = temporary_root / urdf_path.name
    ET.indent(tree, space="  ")
    tree.write(import_urdf_path, encoding="utf-8", xml_declaration=True)
    return import_urdf_path


def _launch_simulation_app():
    from isaacsim import SimulationApp

    app = SimulationApp(
        {
            "headless": True,
            "fast_shutdown": True,
            "extra_args": [
                "--/app/enableStdoutOutput=false",
                "--/app/python/logSysStdOutput=false",
                "--/log/level=error",
                "--/log/outputStreamLevel=error",
            ],
        }
    )
    import omni.kit.app
    from isaacsim.core.utils.extensions import enable_extension

    enable_extension("isaacsim.asset.importer.urdf")
    app_interface = omni.kit.app.get_app()
    while not app_interface.is_app_ready():
        app_interface.update()
    return app


def _relationship_target_name(joint: Any, relationship_name: str) -> tuple[str, Any]:
    relationship = joint.GetPrim().GetRelationship(relationship_name)
    targets = relationship.GetTargets()
    if len(targets) != 1:
        raise ConversionError(f"{joint.GetPath()}.{relationship_name} expected one target, got {targets}")
    return targets[0].name, targets[0]


def _set_armature(prim: Any, value: float, *, axis: str | None = None) -> None:
    prim.ApplyAPI("PhysxJointAPI")
    armature = prim.GetAttribute("physxJoint:armature")
    if not armature or not armature.IsValid():
        raise ConversionError(f"failed to apply PhysxJointAPI to {prim.GetPath()}")
    armature.Set(value)

    if axis is not None:
        prim.ApplyAPI("PhysxJointAxisAPI", axis)
        axis_armature = prim.GetAttribute(f"physxJointAxis:{axis}:armature")
        if not axis_armature or not axis_armature.IsValid():
            raise ConversionError(f"failed to apply PhysxJointAxisAPI:{axis} to {prim.GetPath()}")
        axis_armature.Set(value)


def _set_neutral_tree_joint_physics(prim: Any, damping: float) -> None:
    """Preserve source damping without embedding a controller in the asset."""
    from pxr import UsdPhysics

    prim.ApplyAPI("PhysxJointAxisAPI", "angular")
    for attribute_name, value in (
        ("physxJointAxis:angular:staticFrictionEffort", 0.0),
        ("physxJointAxis:angular:dynamicFrictionEffort", 0.0),
        # PhysX angular joint-axis coefficients are expressed per degree.
        ("physxJointAxis:angular:viscousFrictionCoefficient", math.radians(damping)),
    ):
        attribute = prim.GetAttribute(attribute_name)
        if not attribute or not attribute.IsValid():
            raise ConversionError(f"failed to create {attribute_name} on {prim.GetPath()}")
        attribute.Set(value)

    legacy_friction = prim.GetAttribute("physxJoint:jointFriction")
    if legacy_friction and legacy_friction.IsValid():
        legacy_friction.Block()

    drive = UsdPhysics.DriveAPI.Get(prim, "angular")
    if not drive:
        drive = UsdPhysics.DriveAPI.Apply(prim, "angular")
    drive.CreateTypeAttr("force")
    drive.CreateStiffnessAttr(0.0)
    drive.CreateDampingAttr(0.0)
    drive.CreateMaxForceAttr(0.0)
    drive.GetTargetPositionAttr().Block()
    drive.GetTargetVelocityAttr().Block()


def _remove_transient_visuals(stage: Any, robot_prim_path: Any) -> None:
    """Remove every importer-created dummy visual scope before flattening."""
    removed_paths = []
    missing_paths = []
    root_path = str(robot_prim_path).rstrip("/")
    for link_name in sorted(EXPECTED_LINKS):
        visual_path = f"{root_path}/{link_name}/visuals"
        visual_prim = stage.GetPrimAtPath(visual_path)
        if not visual_prim or not visual_prim.IsValid():
            missing_paths.append(visual_path)
            continue
        visual_path = visual_prim.GetPath()
        removed_paths.append(visual_path)
        # Importer output is composed from generated sublayers.  RemovePrim
        # alone cannot erase a weaker-layer definition, so author an inactive
        # override when the composed prim remains visible.
        stage.RemovePrim(visual_path)
        surviving_prim = stage.GetPrimAtPath(visual_path)
        if surviving_prim and surviving_prim.IsValid():
            stage.OverridePrim(visual_path).SetActive(False)

    if missing_paths:
        raise ConversionError(f"importer did not create expected transient visual scopes: {missing_paths}")
    surviving_paths = [
        str(path)
        for path in removed_paths
        if stage.GetPrimAtPath(path).IsValid() and stage.GetPrimAtPath(path).IsActive()
    ]
    if surviving_paths:
        raise ConversionError(f"failed to remove transient visual scopes: {surviving_paths}")
    if len(removed_paths) != len(EXPECTED_LINKS):
        raise ConversionError(f"expected to remove {len(EXPECTED_LINKS)} visual scopes, got {len(removed_paths)}")


def _normalize_mesh_collision_schemas(stage: Any) -> None:
    """Move importer collision schemas from wrapper Xforms onto mesh leaves.

    The Isaac Sim URDF importer represents an STL collision as a collider API
    on a transform that contains the actual ``UsdGeom.Mesh``.  PhysX accepts
    that representation, but the viewport collider overlay only renders the
    direct primitive colliders in this asset.  Author the equivalent schemas
    on the mesh leaf so the physical and inspection representations agree.
    """
    from pxr import UsdGeom, UsdPhysics

    wrapper_colliders = []
    # This function intentionally runs only after ``Usd.Stage.Export`` has
    # flattened the importer output.  At that point the ``Flattened_Prototype``
    # prims are ordinary editable prims; in the importer stage they are
    # instance proxies and USD forbids authoring on them.
    for prim in stage.TraverseAll():
        if prim.IsA(UsdGeom.Mesh) or not prim.HasAPI(UsdPhysics.CollisionAPI):
            continue
        if not prim.HasAPI(UsdPhysics.MeshCollisionAPI):
            continue
        wrapper_colliders.append(prim)

    if len(wrapper_colliders) != EXPECTED_COLLISION_MESH_COUNT:
        paths = [str(prim.GetPath()) for prim in wrapper_colliders]
        raise ConversionError(
            f"expected one importer mesh-collision wrapper per collision STL, got {len(paths)}: {paths}"
        )

    migrated_meshes = []
    all_prims = list(stage.TraverseAll())
    for wrapper in wrapper_colliders:
        descendants = [
            prim
            for prim in all_prims
            if prim != wrapper and prim.GetPath().HasPrefix(wrapper.GetPath()) and prim.IsA(UsdGeom.Gprim)
        ]
        if len(descendants) != 1 or not descendants[0].IsA(UsdGeom.Mesh):
            paths = [str(prim.GetPath()) for prim in descendants]
            raise ConversionError(
                f"mesh collision wrapper {wrapper.GetPath()} must contain exactly one Mesh leaf, got {paths}"
            )
        mesh_prim = descendants[0]
        wrapper_collision = UsdPhysics.CollisionAPI(wrapper)
        wrapper_mesh_collision = UsdPhysics.MeshCollisionAPI(wrapper)
        collision_enabled = wrapper_collision.GetCollisionEnabledAttr().Get()
        approximation = wrapper_mesh_collision.GetApproximationAttr().Get()
        if collision_enabled is not True:
            raise ConversionError(f"mesh collision wrapper {wrapper.GetPath()} is not enabled")
        if approximation is None:
            raise ConversionError(f"mesh collision wrapper {wrapper.GetPath()} has no approximation")

        UsdPhysics.CollisionAPI.Apply(mesh_prim)
        UsdPhysics.MeshCollisionAPI.Apply(mesh_prim)
        if not mesh_prim.HasAPI(UsdPhysics.CollisionAPI) or not mesh_prim.HasAPI(UsdPhysics.MeshCollisionAPI):
            raise ConversionError(f"failed to author collision schemas on mesh {mesh_prim.GetPath()}")
        UsdPhysics.CollisionAPI(mesh_prim).CreateCollisionEnabledAttr(True)
        UsdPhysics.MeshCollisionAPI(mesh_prim).CreateApproximationAttr(approximation)
        migrated_meshes.append(mesh_prim)

    for wrapper in wrapper_colliders:
        if not wrapper.RemoveAPI(UsdPhysics.MeshCollisionAPI):
            raise ConversionError(f"failed to remove MeshCollisionAPI from wrapper {wrapper.GetPath()}")
        if not wrapper.RemoveAPI(UsdPhysics.CollisionAPI):
            raise ConversionError(f"failed to remove CollisionAPI from wrapper {wrapper.GetPath()}")
        if wrapper.HasAPI(UsdPhysics.CollisionAPI) or wrapper.HasAPI(UsdPhysics.MeshCollisionAPI):
            raise ConversionError(f"collision schemas survived on wrapper {wrapper.GetPath()}")

    if len(migrated_meshes) != EXPECTED_COLLISION_MESH_COUNT:
        raise ConversionError(f"expected to normalize {EXPECTED_COLLISION_MESH_COUNT} mesh colliders")


def _postprocess_imported_stage(stage: Any, source: SourceContract) -> None:
    from pxr import UsdPhysics

    revolute_joints = {}
    spherical_joints = {}
    for prim in stage.Traverse():
        if prim.IsA(UsdPhysics.RevoluteJoint):
            revolute_joints[prim.GetName()] = prim
        elif prim.IsA(UsdPhysics.SphericalJoint):
            spherical_joints[prim.GetName()] = prim

    if set(revolute_joints) != set(EXPECTED_TREE_JOINTS):
        raise ConversionError(f"importer produced unexpected revolute joints: {sorted(revolute_joints)}")
    if set(spherical_joints) != set(EXPECTED_LOOPS):
        raise ConversionError(f"importer produced unexpected spherical joints: {sorted(spherical_joints)}")

    for name, prim in revolute_joints.items():
        _set_armature(prim, EXPECTED_TREE_JOINTS[name][2], axis="angular")
        _set_neutral_tree_joint_physics(prim, EXPECTED_JOINT_DAMPING[name])

    for prim in spherical_joints.values():
        joint = UsdPhysics.Joint(prim)
        joint.CreateExcludeFromArticulationAttr(True)
        joint.CreateJointEnabledAttr(True)
        _set_armature(prim, LOOP_JOINT_ARMATURE)

    root_layer = stage.GetRootLayer()
    metadata = dict(root_layer.customLayerData)
    metadata.update(
        {
            "se3RlLab:generator": "scripts/convert_serialleg_urdf_to_usd.py",
            "se3RlLab:contract": _relative_project_path(CONTRACT_PATH),
            "se3RlLab:contractSha256": CONTRACT_SHA256,
            "se3RlLab:sourceUrdf": source.relative_path,
            "se3RlLab:sourceUrdfSha256": source.sha256,
            "se3RlLab:importerSettings": ",".join(
                f"{key}={str(value).lower()}" for key, value in sorted(IMPORTER_SETTINGS.items())
            ),
            "se3RlLab:loopJointArmature": LOOP_JOINT_ARMATURE,
            "se3RlLab:sourceVisualCount": EXPECTED_VISUAL_COUNT,
            "se3RlLab:transientDummyVisualCount": len(EXPECTED_LINKS),
            "se3RlLab:importCollisionMeshCount": EXPECTED_COLLISION_MESH_COUNT,
            "se3RlLab:visualPolicy": VISUAL_POLICY,
            "se3RlLab:meshCollisionSchemaPolicy": "direct-mesh-leaf",
        }
    )
    root_layer.customLayerData = metadata
    root_layer.Save()


def _canonicalize_flattened_stage(usd_path: Path) -> None:
    """Replace the temporary provenance injected by ``Usd.Stage.Export``."""
    from pxr import Usd

    stage = Usd.Stage.Open(str(usd_path), Usd.Stage.LoadAll)
    if stage is None:
        raise ConversionError(f"failed to reopen flattened USD for metadata normalization: {usd_path}")
    if not stage.SetMetadata("documentation", STAGE_DOCUMENTATION):
        raise ConversionError("failed to author canonical USD stage documentation")
    with tempfile.NamedTemporaryFile(
        prefix=f".{usd_path.stem}.canonical.",
        suffix=usd_path.suffix,
        dir=usd_path.parent,
        delete=False,
    ) as stream:
        canonical_path = Path(stream.name)
    try:
        # Export the already flattened Sdf layer, rather than the composed
        # stage, so no new source-layer documentation is injected.  Writing a
        # fresh crate also drops dead blocks left by in-place USDC updates.
        if not stage.GetRootLayer().Export(str(canonical_path)):
            raise ConversionError(f"failed to export canonical flattened USD: {canonical_path}")
        os.replace(canonical_path, usd_path)
    finally:
        canonical_path.unlink(missing_ok=True)


def _normalize_saved_mesh_collision_schemas(usd_path: Path) -> None:
    """Normalize collider APIs after flattening removes importer instances."""
    from pxr import Usd

    stage = Usd.Stage.Open(str(usd_path), Usd.Stage.LoadAll)
    if stage is None:
        raise ConversionError(f"failed to reopen flattened USD for collision schema normalization: {usd_path}")
    _normalize_mesh_collision_schemas(stage)
    stage.GetRootLayer().Save()


def _validate_layer_metadata(stage: Any, source: SourceContract) -> Any:
    metadata = dict(stage.GetRootLayer().customLayerData)
    if stage.GetMetadata("documentation") != STAGE_DOCUMENTATION:
        raise ConversionError("USD stage documentation contains non-canonical importer provenance")
    if "/tmp/" in stage.GetRootLayer().ExportToString():
        raise ConversionError("USD contains an ephemeral /tmp path")
    if metadata.get("se3RlLab:sourceUrdfSha256") != source.sha256:
        raise ConversionError("USD source hash does not match the current canonical URDF")
    if metadata.get("se3RlLab:sourceUrdf") != source.relative_path:
        raise ConversionError("USD source path metadata does not match the canonical URDF")
    if metadata.get("se3RlLab:contract") != _relative_project_path(CONTRACT_PATH):
        raise ConversionError("USD contract path metadata does not match the canonical contract")
    if metadata.get("se3RlLab:contractSha256") != CONTRACT_SHA256:
        raise ConversionError("USD contract hash does not match the canonical contract")
    expected_importer_settings = ",".join(
        f"{key}={str(value).lower()}" for key, value in sorted(IMPORTER_SETTINGS.items())
    )
    if metadata.get("se3RlLab:importerSettings") != expected_importer_settings:
        raise ConversionError("USD importer settings metadata does not match the canonical contract")
    _assert_close(
        float(metadata.get("se3RlLab:loopJointArmature", float("nan"))),
        LOOP_JOINT_ARMATURE,
        "USD loop armature metadata",
    )
    if metadata.get("se3RlLab:visualPolicy") != VISUAL_POLICY:
        raise ConversionError("USD visual policy metadata does not match the collision-only contract")
    if int(metadata.get("se3RlLab:sourceVisualCount", -1)) != EXPECTED_VISUAL_COUNT:
        raise ConversionError("USD source visual count metadata does not match the canonical URDF")
    if int(metadata.get("se3RlLab:transientDummyVisualCount", -1)) != len(EXPECTED_LINKS):
        raise ConversionError("USD transient visual count metadata does not match the importer contract")
    if int(metadata.get("se3RlLab:importCollisionMeshCount", -1)) != EXPECTED_COLLISION_MESH_COUNT:
        raise ConversionError("USD collision mesh count metadata does not match the importer contract")
    if metadata.get("se3RlLab:meshCollisionSchemaPolicy") != "direct-mesh-leaf":
        raise ConversionError("USD mesh collision schema policy is not direct-mesh-leaf")

    default_prim = stage.GetDefaultPrim()
    if not default_prim or not default_prim.IsValid():
        raise ConversionError("USD has no valid default prim")
    if default_prim.GetName() != EXPECTED_ROBOT_NAME:
        raise ConversionError(f"unexpected USD default prim: {default_prim.GetPath()}")
    return default_prim


def _collect_stage_inventory(stage: Any) -> StageInventory:
    from pxr import Usd, UsdGeom, UsdPhysics

    def has_path_component(prim: Any, component: str) -> bool:
        return component in {part.lower() for part in str(prim.GetPath()).split("/") if part}

    def has_collision_api_ancestor(prim: Any) -> bool:
        ancestor = prim
        while ancestor and ancestor.IsValid() and not ancestor.IsPseudoRoot():
            if ancestor.HasAPI(UsdPhysics.CollisionAPI):
                return True
            ancestor = ancestor.GetParent()
        return False

    link_prims: dict[str, Any] = {}
    rigid_body_prims = []
    articulation_roots = []
    revolute_joints: dict[str, Any] = {}
    spherical_joints: dict[str, Any] = {}
    geometry_prims = []
    collision_geometry = []
    visual_geometry = []
    meshes = []
    non_collision_geometry = []
    collision_roots = []
    visual_roots = []
    collision_api_prims = []
    mesh_collision_api_prims = []
    cylinders = []
    capsules = []
    unexpected_joint_prims = []

    # Geometry assets are instanced by the importer, so include instance
    # proxies while inventorying the flattened stage.
    for prim in Usd.PrimRange(stage.GetPseudoRoot(), Usd.TraverseInstanceProxies()):
        if prim.GetName() == "collisions" and prim.GetParent().GetName() in EXPECTED_LINKS:
            collision_roots.append(prim)
        if prim.GetName() == "visuals" and prim.GetParent().GetName() in EXPECTED_LINKS:
            visual_roots.append(prim)
        if prim.HasAPI(UsdPhysics.CollisionAPI):
            collision_api_prims.append(prim)
        if any("MeshCollisionAPI" in schema for schema in prim.GetAppliedSchemas()):
            mesh_collision_api_prims.append(prim)
        if prim.HasAPI(UsdPhysics.RigidBodyAPI):
            rigid_body_prims.append(prim)
            if prim.GetName() in EXPECTED_LINKS:
                if prim.GetName() in link_prims:
                    raise ConversionError(f"duplicate rigid-body link prim named {prim.GetName()}")
                link_prims[prim.GetName()] = prim
        if prim.HasAPI(UsdPhysics.ArticulationRootAPI):
            articulation_roots.append(prim)
        if prim.IsA(UsdPhysics.RevoluteJoint):
            if prim.GetName() in revolute_joints:
                raise ConversionError(f"duplicate revolute joint prim named {prim.GetName()}")
            revolute_joints[prim.GetName()] = prim
        elif prim.IsA(UsdPhysics.SphericalJoint):
            if prim.GetName() in spherical_joints:
                raise ConversionError(f"duplicate spherical joint prim named {prim.GetName()}")
            spherical_joints[prim.GetName()] = prim
        elif prim.IsA(UsdPhysics.Joint):
            unexpected_joint_prims.append(prim)
        if prim.IsA(UsdGeom.Gprim):
            geometry_prims.append(prim)
            if has_path_component(prim, "collisions"):
                collision_geometry.append(prim)
            if has_path_component(prim, "visuals"):
                visual_geometry.append(prim)
            if not has_collision_api_ancestor(prim):
                non_collision_geometry.append(prim)
        if prim.IsA(UsdGeom.Mesh):
            meshes.append(prim)
        if prim.IsA(UsdGeom.Cylinder):
            cylinders.append(prim)
        if prim.IsA(UsdGeom.Capsule):
            capsules.append(prim)

    authored_non_collision_geometry = [
        prim for prim in stage.TraverseAll() if prim.IsA(UsdGeom.Gprim) and not has_collision_api_ancestor(prim)
    ]

    return StageInventory(
        links=link_prims,
        rigid_bodies=rigid_body_prims,
        articulation_roots=articulation_roots,
        revolute_joints=revolute_joints,
        spherical_joints=spherical_joints,
        unexpected_joints=unexpected_joint_prims,
        geometry_prims=geometry_prims,
        collision_geometry=collision_geometry,
        visual_geometry=visual_geometry,
        meshes=meshes,
        non_collision_geometry=non_collision_geometry,
        authored_non_collision_geometry=authored_non_collision_geometry,
        collision_roots=collision_roots,
        visual_roots=visual_roots,
        collision_api_prims=collision_api_prims,
        mesh_collision_api_prims=mesh_collision_api_prims,
        cylinders=cylinders,
        capsules=capsules,
    )


def _validate_articulation(inventory: StageInventory) -> Any:
    from pxr import PhysxSchema

    if set(inventory.links) != EXPECTED_LINKS:
        raise ConversionError(f"USD rigid-body link set changed: {sorted(inventory.links)}")
    if len(inventory.rigid_bodies) != len(EXPECTED_LINKS):
        paths = [str(prim.GetPath()) for prim in inventory.rigid_bodies]
        raise ConversionError(f"expected exactly 11 rigid bodies, got {len(paths)}: {paths}")
    if len(inventory.articulation_roots) != 1 or inventory.articulation_roots[0].GetName() != "base_link":
        paths = [str(prim.GetPath()) for prim in inventory.articulation_roots]
        raise ConversionError(f"expected one articulation root on base_link, got {paths}")
    articulation_root = inventory.articulation_roots[0]
    if not articulation_root.HasAPI(PhysxSchema.PhysxArticulationAPI):
        raise ConversionError("base_link is missing PhysxArticulationAPI")
    self_collision = articulation_root.GetAttribute("physxArticulation:enabledSelfCollisions")
    if self_collision and self_collision.IsValid() and self_collision.Get() is not False:
        raise ConversionError("articulation self-collision must be disabled in the generated asset")
    return articulation_root


def _validate_joint_sets(inventory: StageInventory) -> None:
    if set(inventory.revolute_joints) != set(EXPECTED_TREE_JOINTS):
        raise ConversionError(f"unexpected USD tree joint set: {sorted(inventory.revolute_joints)}")
    if set(inventory.spherical_joints) != set(EXPECTED_LOOPS):
        raise ConversionError(f"unexpected USD loop joint set: {sorted(inventory.spherical_joints)}")
    if inventory.unexpected_joints:
        raise ConversionError(
            "unexpected non-revolute/non-spherical joints: "
            + ", ".join(str(prim.GetPath()) for prim in inventory.unexpected_joints)
        )


def _validate_physics_prim_paths(inventory: StageInventory, default_prim: Any) -> None:
    root_path = default_prim.GetPath()
    physics_prims = (
        inventory.rigid_bodies
        + inventory.articulation_roots
        + list(inventory.revolute_joints.values())
        + list(inventory.spherical_joints.values())
        + inventory.unexpected_joints
    )
    outside_root = [str(prim.GetPath()) for prim in physics_prims if not prim.GetPath().HasPrefix(root_path)]
    if outside_root:
        raise ConversionError(f"physics prims exist outside the default robot prim: {outside_root}")


def _validate_tree_joints(inventory: StageInventory) -> list[tuple[str, str]]:
    from pxr import UsdPhysics

    tree_edges = []
    for name, (expected_parent, expected_child, expected_armature) in EXPECTED_TREE_JOINTS.items():
        prim = inventory.revolute_joints[name]
        joint = UsdPhysics.Joint(prim)
        parent, parent_path = _relationship_target_name(joint, "physics:body0")
        child, child_path = _relationship_target_name(joint, "physics:body1")
        if (parent, child) != (expected_parent, expected_child):
            raise ConversionError(
                f"{name} body relationship changed: expected {expected_parent}->{expected_child}, got {parent}->{child}"
            )
        if parent_path != inventory.links[parent].GetPath() or child_path != inventory.links[child].GetPath():
            raise ConversionError(f"{name} body relationship does not target the validated link prims")
        excluded = joint.GetExcludeFromArticulationAttr()
        if excluded and excluded.HasAuthoredValueOpinion() and bool(excluded.Get()):
            raise ConversionError(f"tree joint {name} must remain inside the articulation")
        armature = prim.GetAttribute("physxJoint:armature")
        axis_armature = prim.GetAttribute("physxJointAxis:angular:armature")
        if not armature or not armature.HasAuthoredValueOpinion():
            raise ConversionError(f"{name} is missing authored joint armature")
        if not axis_armature or not axis_armature.HasAuthoredValueOpinion():
            raise ConversionError(f"{name} is missing authored angular-axis armature")
        _assert_close(float(armature.Get()), expected_armature, f"{name} joint armature")
        _assert_close(float(axis_armature.Get()), expected_armature, f"{name} angular armature")
        viscous_friction = prim.GetAttribute("physxJointAxis:angular:viscousFrictionCoefficient")
        if not viscous_friction or not viscous_friction.HasAuthoredValueOpinion():
            raise ConversionError(f"{name} is missing authored viscous damping")
        _assert_close(
            float(viscous_friction.Get()),
            math.radians(EXPECTED_JOINT_DAMPING[name]),
            f"{name} viscous damping",
        )
        drive = UsdPhysics.DriveAPI.Get(prim, "angular")
        if not drive:
            raise ConversionError(f"{name} is missing the neutral angular DriveAPI")
        if drive.GetTypeAttr().Get() != "force":
            raise ConversionError(f"{name} drive type must be force")
        for attribute, label in (
            (drive.GetStiffnessAttr(), "stiffness"),
            (drive.GetDampingAttr(), "damping"),
            (drive.GetMaxForceAttr(), "max force"),
        ):
            if not attribute.HasAuthoredValueOpinion():
                raise ConversionError(f"{name} drive {label} must be explicitly authored")
            _assert_close(float(attribute.Get()), 0.0, f"{name} drive {label}")
        for attribute, label in (
            (drive.GetTargetPositionAttr(), "target position"),
            (drive.GetTargetVelocityAttr(), "target velocity"),
        ):
            if attribute.Get() is not None:
                raise ConversionError(f"{name} drive {label} must be blocked")
        for attribute_name in ("physics:lowerLimit", "physics:upperLimit"):
            limit = prim.GetAttribute(attribute_name)
            if limit and limit.HasAuthoredValueOpinion() and math.isfinite(float(limit.Get())):
                raise ConversionError(f"{name} must not have a finite independent joint limit")
        tree_edges.append((parent, child))
    return tree_edges


def _validate_connected_tree(tree_edges: list[tuple[str, str]]) -> None:
    adjacency = {link: set() for link in EXPECTED_LINKS}
    for parent, child in tree_edges:
        adjacency[parent].add(child)
        adjacency[child].add(parent)
    visited = set()
    pending = ["base_link"]
    while pending:
        link = pending.pop()
        if link in visited:
            continue
        visited.add(link)
        pending.extend(adjacency[link] - visited)
    if visited != EXPECTED_LINKS or len(tree_edges) != len(EXPECTED_LINKS) - 1:
        raise ConversionError("the articulation joint graph is not one connected tree")


def _validate_loop_joints(inventory: StageInventory) -> None:
    from pxr import UsdPhysics

    for name, (expected_body0, position0, expected_body1, position1) in EXPECTED_LOOPS.items():
        prim = inventory.spherical_joints[name]
        joint = UsdPhysics.Joint(prim)
        body0, body0_path = _relationship_target_name(joint, "physics:body0")
        body1, body1_path = _relationship_target_name(joint, "physics:body1")
        if (body0, body1) != (expected_body0, expected_body1):
            raise ConversionError(
                f"{name} body relationship changed: expected {expected_body0}->{expected_body1}, got {body0}->{body1}"
            )
        if body0_path != inventory.links[body0].GetPath() or body1_path != inventory.links[body1].GetPath():
            raise ConversionError(f"{name} does not target the validated rigid-body link prims")
        _assert_vector_close(joint.GetLocalPos0Attr().Get(), position0, f"{name}.localPos0")
        _assert_vector_close(joint.GetLocalPos1Attr().Get(), position1, f"{name}.localPos1")
        for suffix, quaternion in (
            ("localRot0", joint.GetLocalRot0Attr().Get()),
            ("localRot1", joint.GetLocalRot1Attr().Get()),
        ):
            _assert_close(abs(float(quaternion.GetReal())), 1.0, f"{name}.{suffix}.real")
            _assert_vector_close(quaternion.GetImaginary(), (0.0, 0.0, 0.0), f"{name}.{suffix}.imaginary")
        excluded = joint.GetExcludeFromArticulationAttr()
        if not excluded or not excluded.HasAuthoredValueOpinion() or excluded.Get() is not True:
            raise ConversionError(f"{name} must author physics:excludeFromArticulation=true")
        if joint.GetJointEnabledAttr().Get() is not True:
            raise ConversionError(f"{name} must be enabled")
        armature = prim.GetAttribute("physxJoint:armature")
        if not armature or not armature.HasAuthoredValueOpinion():
            raise ConversionError(f"{name} is missing loop-joint armature")
        _assert_close(float(armature.Get()), LOOP_JOINT_ARMATURE, f"{name} armature")
        if any("PhysicsDriveAPI" in schema for schema in prim.GetAppliedSchemas()):
            raise ConversionError(f"{name} must not have a drive API")


def _validate_mass_and_shapes(inventory: StageInventory) -> tuple[float, int]:
    from pxr import UsdGeom, UsdPhysics

    total_mass = 0.0
    for name, prim in inventory.links.items():
        mass = UsdPhysics.MassAPI(prim).GetMassAttr()
        if not mass or not mass.HasAuthoredValueOpinion():
            raise ConversionError(f"{name} has no authored mass")
        total_mass += float(mass.Get())
    _assert_close(total_mass, EXPECTED_TOTAL_MASS, "USD total mass", tolerance=1.0e-6)

    collision_root_links = {prim.GetParent().GetName() for prim in inventory.collision_roots}
    if collision_root_links != EXPECTED_LINKS or len(inventory.collision_roots) != len(EXPECTED_LINKS):
        paths = [str(prim.GetPath()) for prim in inventory.collision_roots]
        raise ConversionError(f"expected one collision scope per link, got {paths}")
    if inventory.visual_roots:
        paths = [str(prim.GetPath()) for prim in inventory.visual_roots]
        raise ConversionError(f"collision-only USD contains active visual scopes: {paths}")
    if inventory.visual_geometry:
        paths = [str(prim.GetPath()) for prim in inventory.visual_geometry]
        raise ConversionError(f"collision-only USD contains active visual geometry: {paths}")
    if len(inventory.geometry_prims) != EXPECTED_COLLISION_MESH_COUNT + 2:
        raise ConversionError(f"expected 56 collision geometry prims, got {len(inventory.geometry_prims)}")
    if len(inventory.collision_geometry) != len(inventory.geometry_prims):
        paths = [str(prim.GetPath()) for prim in inventory.geometry_prims if prim not in inventory.collision_geometry]
        raise ConversionError(f"active geometry exists outside collision scopes: {paths}")
    if inventory.non_collision_geometry:
        paths = [str(prim.GetPath()) for prim in inventory.non_collision_geometry]
        raise ConversionError(f"collision-only USD contains visual or unclassified geometry: {paths}")
    if inventory.authored_non_collision_geometry:
        paths = [str(prim.GetPath()) for prim in inventory.authored_non_collision_geometry]
        raise ConversionError(f"flattened USD contains orphan non-collision geometry: {paths}")
    if len(inventory.collision_api_prims) != EXPECTED_COLLISION_MESH_COUNT + 2:
        raise ConversionError(f"expected 56 CollisionAPI prims, got {len(inventory.collision_api_prims)}")
    if any("collisions" not in str(prim.GetPath()).split("/") for prim in inventory.collision_api_prims):
        paths = [str(prim.GetPath()) for prim in inventory.collision_api_prims]
        raise ConversionError(f"CollisionAPI prim exists outside collision scopes: {paths}")
    non_geometry_colliders = [prim for prim in inventory.collision_api_prims if not prim.IsA(UsdGeom.Gprim)]
    if non_geometry_colliders:
        paths = [str(prim.GetPath()) for prim in non_geometry_colliders]
        raise ConversionError(f"collision schemas must be authored on geometry leaves, not wrappers: {paths}")
    disabled_colliders = [
        prim
        for prim in inventory.collision_api_prims
        if UsdPhysics.CollisionAPI(prim).GetCollisionEnabledAttr().Get() is not True
    ]
    if disabled_colliders:
        paths = [str(prim.GetPath()) for prim in disabled_colliders]
        raise ConversionError(f"collision geometry is unexpectedly disabled: {paths}")
    if len(inventory.mesh_collision_api_prims) != EXPECTED_COLLISION_MESH_COUNT:
        raise ConversionError(
            f"expected {EXPECTED_COLLISION_MESH_COUNT} mesh collision API prims, "
            f"got {len(inventory.mesh_collision_api_prims)}"
        )
    if len(inventory.meshes) != EXPECTED_COLLISION_MESH_COUNT:
        raise ConversionError(f"expected {EXPECTED_COLLISION_MESH_COUNT} collision meshes, got {len(inventory.meshes)}")
    mesh_without_direct_collider = [prim for prim in inventory.meshes if not prim.HasAPI(UsdPhysics.CollisionAPI)]
    if mesh_without_direct_collider:
        paths = [str(prim.GetPath()) for prim in mesh_without_direct_collider]
        raise ConversionError(f"collision mesh lacks direct CollisionAPI: {paths}")
    mesh_without_direct_mesh_collider = [
        prim for prim in inventory.meshes if not prim.HasAPI(UsdPhysics.MeshCollisionAPI)
    ]
    if mesh_without_direct_mesh_collider:
        paths = [str(prim.GetPath()) for prim in mesh_without_direct_mesh_collider]
        raise ConversionError(f"collision mesh lacks direct MeshCollisionAPI: {paths}")
    unexpected_mesh_collision_api_prims = [
        prim for prim in inventory.mesh_collision_api_prims if not prim.IsA(UsdGeom.Mesh)
    ]
    if unexpected_mesh_collision_api_prims:
        paths = [str(prim.GetPath()) for prim in unexpected_mesh_collision_api_prims]
        raise ConversionError(f"MeshCollisionAPI must be authored on Mesh prims: {paths}")
    non_convex_hull_meshes = [
        prim
        for prim in inventory.meshes
        if UsdPhysics.MeshCollisionAPI(prim).GetApproximationAttr().Get() != UsdPhysics.Tokens.convexHull
    ]
    if non_convex_hull_meshes:
        paths = [str(prim.GetPath()) for prim in non_convex_hull_meshes]
        raise ConversionError(f"collision mesh approximation changed from convexHull: {paths}")
    if len(inventory.cylinders) != 2:
        raise ConversionError(f"expected two preserved wheel cylinders, got {len(inventory.cylinders)}")
    if inventory.capsules:
        raise ConversionError(
            f"cylinder replacement was unexpectedly enabled: found {len(inventory.capsules)} capsules"
        )
    for cylinder in inventory.cylinders:
        cylinder_schema = cylinder if hasattr(cylinder, "GetRadiusAttr") else None
        if cylinder_schema is None:
            cylinder_schema = UsdGeom.Cylinder(cylinder)
        _assert_close(float(cylinder_schema.GetRadiusAttr().Get()), 0.06, f"{cylinder.GetPath()} radius")
        _assert_close(float(cylinder_schema.GetHeightAttr().Get()), 0.02, f"{cylinder.GetPath()} height")

    face_count = 0
    point_count = 0
    index_count = 0
    for prim in inventory.meshes:
        mesh = UsdGeom.Mesh(prim)
        face_count += len(mesh.GetFaceVertexCountsAttr().Get() or [])
        point_count += len(mesh.GetPointsAttr().Get() or [])
        index_count += len(mesh.GetFaceVertexIndicesAttr().Get() or [])
    if face_count != EXPECTED_COLLISION_FACE_COUNT:
        raise ConversionError(f"collision mesh face count changed: expected 7102, got {face_count}")
    if point_count != EXPECTED_COLLISION_POINT_INDEX_COUNT:
        raise ConversionError(f"collision mesh point count changed: expected 21306, got {point_count}")
    if index_count != EXPECTED_COLLISION_POINT_INDEX_COUNT:
        raise ConversionError(f"collision mesh index count changed: expected 21306, got {index_count}")
    return total_mass, face_count


def _validate_saved_usd(usd_path: Path, source: SourceContract) -> dict[str, Any]:
    from pxr import Usd, UsdGeom, UsdPhysics, UsdUtils

    if not usd_path.is_file():
        raise ConversionError(f"USD does not exist: {usd_path}")
    usd_size = usd_path.stat().st_size
    if usd_size > MAX_COLLISION_ONLY_USD_BYTES:
        raise ConversionError(
            f"collision-only USD is unexpectedly large: {usd_size} bytes > {MAX_COLLISION_ONLY_USD_BYTES}"
        )
    stage = Usd.Stage.Open(str(usd_path), Usd.Stage.LoadAll)
    if stage is None:
        raise ConversionError(f"failed to open USD: {usd_path}")
    _assert_close(float(UsdGeom.GetStageMetersPerUnit(stage)), 1.0, "USD metersPerUnit")
    if UsdGeom.GetStageUpAxis(stage) != UsdGeom.Tokens.z:
        raise ConversionError(f"USD up axis must be Z, got {UsdGeom.GetStageUpAxis(stage)}")
    if any(prim.IsA(UsdPhysics.Scene) for prim in stage.Traverse()):
        raise ConversionError("generated robot asset must not contain a PhysicsScene")

    default_prim = _validate_layer_metadata(stage, source)
    inventory = _collect_stage_inventory(stage)
    _validate_physics_prim_paths(inventory, default_prim)
    articulation_root = _validate_articulation(inventory)
    _validate_joint_sets(inventory)
    _validate_connected_tree(_validate_tree_joints(inventory))
    _validate_loop_joints(inventory)
    total_mass, collision_faces = _validate_mass_and_shapes(inventory)

    _layers, _assets, unresolved = UsdUtils.ComputeAllDependencies(str(usd_path))
    if unresolved:
        raise ConversionError(f"USD has unresolved dependencies: {sorted(str(path) for path in unresolved)}")

    return {
        "default_prim": str(default_prim.GetPath()),
        "articulation_root": str(articulation_root.GetPath()),
        "links": len(inventory.links),
        "tree_joints": len(inventory.revolute_joints),
        "loop_joints": len(inventory.spherical_joints),
        "total_mass": total_mass,
        "usd_bytes": usd_size,
        "collision_meshes": len(inventory.meshes),
        "collision_faces": collision_faces,
        "visual_geometries": len(inventory.non_collision_geometry),
        "cylinders": len(inventory.cylinders),
    }


def _import_to_usd(urdf_path: Path, output_path: Path, source: SourceContract) -> dict[str, Any]:
    print("[serialleg-usd] loading URDF importer modules...", flush=True)
    import omni.kit.commands
    from isaacsim.asset.importer.urdf import _urdf
    from pxr import Usd

    print("[serialleg-usd] URDF importer modules are ready", flush=True)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="serialleg_urdf_import_") as temporary_directory:
        temporary_root = Path(temporary_directory)
        import_urdf_path = _build_collision_only_import_urdf(urdf_path, temporary_root)
        imported_path = temporary_root / output_path.name

        config = _urdf.ImportConfig()
        setters = (
            ("fix_base", config.set_fix_base, IMPORTER_SETTINGS["fix_base"]),
            ("merge_fixed_joints", config.set_merge_fixed_joints, IMPORTER_SETTINGS["merge_fixed_joints"]),
            ("import_inertia_tensor", config.set_import_inertia_tensor, IMPORTER_SETTINGS["import_inertia_tensor"]),
            ("make_default_prim", config.set_make_default_prim, IMPORTER_SETTINGS["make_default_prim"]),
            ("create_physics_scene", config.set_create_physics_scene, IMPORTER_SETTINGS["create_physics_scene"]),
            ("self_collision", config.set_self_collision, IMPORTER_SETTINGS["self_collision"]),
            (
                "collision_from_visuals",
                config.set_collision_from_visuals,
                IMPORTER_SETTINGS["collision_from_visuals"],
            ),
            (
                "replace_cylinders_with_capsules",
                config.set_replace_cylinders_with_capsules,
                IMPORTER_SETTINGS["replace_cylinders_with_capsules"],
            ),
        )
        for _setting_name, setter, value in setters:
            setter(value)

        print(
            "[serialleg-usd] importer configuration is ready; "
            f"stripped_visuals={EXPECTED_VISUAL_COUNT} transient_dummy_visuals={len(EXPECTED_LINKS)} "
            f"retained_collision_meshes={EXPECTED_COLLISION_MESH_COUNT}",
            flush=True,
        )
        print(f"[serialleg-usd] importing URDF into temporary stage: {imported_path}", flush=True)
        status, prim_path = omni.kit.commands.execute(
            "URDFParseAndImportFile",
            urdf_path=str(import_urdf_path),
            import_config=config,
            dest_path=str(imported_path),
        )
        if not status:
            raise ConversionError(f"Isaac URDF importer failed for {urdf_path}")
        print(f"[serialleg-usd] importer returned root prim: {prim_path}", flush=True)

        stage = Usd.Stage.Open(str(imported_path), Usd.Stage.LoadAll)
        if stage is None:
            raise ConversionError(f"failed to open importer output: {imported_path}")
        if not stage.GetPrimAtPath(prim_path):
            raise ConversionError(f"importer returned invalid prim path: {prim_path}")
        print("[serialleg-usd] removing transient dummy visual scopes...", flush=True)
        _remove_transient_visuals(stage, prim_path)
        print("[serialleg-usd] applying external-loop and joint-physics postprocess...", flush=True)
        _postprocess_imported_stage(stage, source)

        with tempfile.NamedTemporaryFile(
            prefix=f".{output_path.stem}.",
            suffix=".usd",
            dir=output_path.parent,
            delete=False,
        ) as stream:
            atomic_path = Path(stream.name)
        try:
            if not stage.Export(str(atomic_path)):
                raise ConversionError(f"failed to flatten imported stage into {atomic_path}")
            print("[serialleg-usd] normalizing mesh collision schemas onto Mesh leaves...", flush=True)
            _normalize_saved_mesh_collision_schemas(atomic_path)
            _canonicalize_flattened_stage(atomic_path)
            print("[serialleg-usd] validating flattened USD from disk...", flush=True)
            summary = _validate_saved_usd(atomic_path, source)
            os.replace(atomic_path, output_path)
            output_path.chmod(0o644)
        finally:
            atomic_path.unlink(missing_ok=True)

    return summary


def main() -> int:
    args = _parse_args()
    app = None
    try:
        urdf_path = args.urdf.resolve()
        output_path = args.output.resolve()
        source = _validate_urdf(urdf_path)

        print("[serialleg-usd] starting Isaac Sim 5.1 headless...", flush=True)
        app = _launch_simulation_app()
        print("[serialleg-usd] Isaac Sim is ready", flush=True)
        if args.check:
            summary = _validate_saved_usd(output_path, source)
            action = "checked"
        else:
            summary = _import_to_usd(urdf_path, output_path, source)
            action = "wrote"

        print(f"[serialleg-usd] {action}: {output_path}", flush=True)
        print(
            "[serialleg-usd] "
            f"default_prim={summary['default_prim']} articulation_root={summary['articulation_root']} "
            f"links={summary['links']} tree_joints={summary['tree_joints']} "
            f"external_loop_joints={summary['loop_joints']} collision_meshes={summary['collision_meshes']} "
            f"collision_faces={summary['collision_faces']} cylinders={summary['cylinders']} "
            f"visual_geometries={summary['visual_geometries']} usd_bytes={summary['usd_bytes']} "
            f"total_mass={summary['total_mass']:.8f}kg",
            flush=True,
        )
        app.close(wait_for_replicator=False)
        return 0
    except (ConversionError, ET.ParseError, ImportError, OSError, RuntimeError, ValueError) as error:
        print(f"[serialleg-usd][error] {type(error).__name__}: {error}", file=sys.stderr, flush=True)
        # Kit's fast shutdown exits the process with status 0 before Python can
        # return from close().  On a validated error path, terminate directly
        # so CI and --check callers receive the correct failure status.
        if app is not None:
            sys.stdout.flush()
            sys.stderr.flush()
            os._exit(1)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
